/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=services/sync-worker/wrangler.jsonc --env=staging --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=SyncWorkerEnv services/sync-worker/worker-configuration.d.ts` (hash: 87efd2c0a5bcea1702d42ed38b5a4a70)
interface __BaseEnv_SyncWorkerEnv {
  MIRNA_SYNC_BUCKET: R2Bucket;
  MIRNA_SYNC_DB: D1Database;
  MIRNA_HEALTH_RATE_LIMITER: RateLimit;
  MIRNA_SETUP_RATE_LIMITER: RateLimit;
  MIRNA_PAIRING_CREATE_RATE_LIMITER: RateLimit;
  MIRNA_PAIRING_ACTION_RATE_LIMITER: RateLimit;
  MIRNA_AUTH_CHALLENGE_RATE_LIMITER: RateLimit;
  MIRNA_AUTH_SESSION_RATE_LIMITER: RateLimit;
  MIRNA_RECOVERY_INIT_RATE_LIMITER: RateLimit;
  MIRNA_RECOVERY_ACTION_RATE_LIMITER: RateLimit;
  MIRNA_SYNC_READ_RATE_LIMITER: RateLimit;
  MIRNA_ENVIRONMENT: string;
  MIRNA_BUILD_COMMIT: string;
  MIRNA_PROTOCOL_VERSION: string;
  MIRNA_ALLOWED_ORIGINS: string;
  MIRNA_CLEANUP_BATCH_SIZE: string;
  MIRNA_EPHEMERAL_CLEANUP_BATCH_SIZE: string;
  MIRNA_MAX_TOTAL_VAULTS: string;
  MIRNA_MAX_TOTAL_PAIRING_REQUESTS: string;
  MIRNA_MAX_ACTIVE_AUTH_CHALLENGES_PER_DEVICE: string;
  MIRNA_MAX_ACTIVE_SESSIONS_PER_DEVICE: string;
  MIRNA_MAX_DEVICES_PER_VAULT: string;
  MIRNA_MAX_ACTIVE_PAIRINGS_PER_VAULT: string;
  MIRNA_PAIRING_LIFETIME_SECONDS: string;
  MIRNA_CHALLENGE_LIFETIME_SECONDS: string;
  MIRNA_ACCESS_SESSION_LIFETIME_SECONDS: string;
  MIRNA_DEVICE_AUTHORIZATION_LIFETIME_SECONDS: string;
  MIRNA_MAX_SNAPSHOT_BYTES: string;
  MIRNA_MAX_OPERATION_BYTES: string;
  MIRNA_MAX_OPERATIONS_PER_BATCH: string;
  MIRNA_MAX_RETAINED_SNAPSHOTS: string;
  MIRNA_ORPHAN_LIFETIME_SECONDS: string;
  MIRNA_MAX_RECOVERY_ATTEMPTS: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env extends __BaseEnv_SyncWorkerEnv {}
}
interface SyncWorkerEnv extends __BaseEnv_SyncWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'MIRNA_ENVIRONMENT'
      | 'MIRNA_BUILD_COMMIT'
      | 'MIRNA_PROTOCOL_VERSION'
      | 'MIRNA_ALLOWED_ORIGINS'
      | 'MIRNA_CLEANUP_BATCH_SIZE'
      | 'MIRNA_EPHEMERAL_CLEANUP_BATCH_SIZE'
      | 'MIRNA_MAX_TOTAL_VAULTS'
      | 'MIRNA_MAX_TOTAL_PAIRING_REQUESTS'
      | 'MIRNA_MAX_ACTIVE_AUTH_CHALLENGES_PER_DEVICE'
      | 'MIRNA_MAX_ACTIVE_SESSIONS_PER_DEVICE'
      | 'MIRNA_MAX_DEVICES_PER_VAULT'
      | 'MIRNA_MAX_ACTIVE_PAIRINGS_PER_VAULT'
      | 'MIRNA_PAIRING_LIFETIME_SECONDS'
      | 'MIRNA_CHALLENGE_LIFETIME_SECONDS'
      | 'MIRNA_ACCESS_SESSION_LIFETIME_SECONDS'
      | 'MIRNA_DEVICE_AUTHORIZATION_LIFETIME_SECONDS'
      | 'MIRNA_MAX_SNAPSHOT_BYTES'
      | 'MIRNA_MAX_OPERATION_BYTES'
      | 'MIRNA_MAX_OPERATIONS_PER_BATCH'
      | 'MIRNA_MAX_RETAINED_SNAPSHOTS'
      | 'MIRNA_ORPHAN_LIFETIME_SECONDS'
      | 'MIRNA_MAX_RECOVERY_ATTEMPTS'
    >
  > {}
}
